import { onCall } from "firebase-functions/v2/https";

const stub = onCall(() => {
  return { status: "stubbed", message: "Function temporarily stubbed to prevent deletion during deployment." };
});

export const deleteCustomer = stub;
export const deleteCustomerAddress = stub;
export const deleteDeliveryZone = stub;
export const deleteProduct = stub;
export const deleteStorefrontCategory = stub;
export const deleteSupplier = stub;
export const disableStorefront = stub;
export const enableStorefront = stub;
export const getActiveHolds = stub;
export const getCart = stub;
export const getCarts = stub;
export const getCheckoutAttempts = stub;
export const getCommerceAnalytics = stub;
export const getCommerceTemplates = stub;
export const getCustomerAddresses = stub;
export const getDeliveryZones = stub;
export const getOnlineOrder = stub;
export const getOnlineOrders = stub;
export const getOrderMetrics = stub;
export const getOrderReturns = stub;
export const getPublicCategories = stub;
export const getPublicProductDetails = stub;
export const getPublicProducts = stub;
export const getPublicStorefront = stub;
export const getStorefrontCategories = stub;
export const getStorefrontSettings = stub;
export const processFailedSyncRetries = stub;
export const processRefund = stub;
export const processStaleCheckouts = stub;
export const recordCheckoutAttempt = stub;
export const rejectReturn = stub;
export const releaseExpiredHolds = stub;
export const releaseStockHold = stub;
export const removeFromCart = stub;
export const requestReturn = stub;
export const resetCommerceTemplate = stub;
export const retryCheckout = stub;
export const rollupAnalytics = stub;
export const saveCustomerAddress = stub;
export const scanAbandonedCarts = stub;
export const trackEvent = stub;
export const updateCartQuantity = stub;
export const updateCommerceTemplate = stub;
export const updateDeliveryZone = stub;
export const updateOrderStatus = stub;
export const updateStorefrontCategory = stub;
export const updateStorefrontSettings = stub;
