version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
    groups:
      all-npm-updates:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-pub-updates:
        patterns:
          - "*"
