subprojects { subproject ->
    def applyNamespace = {
        if (subproject.name == "blue_thermal_printer") {
            if (subproject.hasProperty("android")) {
                subproject.android {
                    namespace "id.kakzaki.blue_thermal_printer"
                }
            }
        }
    }

    if (subproject.state.executed) {
        applyNamespace()
    } else {
        subproject.afterEvaluate {
            applyNamespace()
        }
    }
}
