// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZwl2J6-MQl_ZcRD794yT61FEhp9Sirv4',
    appId: '1:156906942756:web:7fc65c7b6c0a32ad3643b1',
    messagingSenderId: '156906942756',
    projectId: 'hardwareos-saas',
    authDomain: 'hardwareos-saas.firebaseapp.com',
    storageBucket: 'hardwareos-saas.firebasestorage.app',
    measurementId: 'G-JMNNBYQPG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDck9XeCzIm-Uam6J-m118xd2SzFyqDhhU',
    appId: '1:156906942756:android:1d76ea4d058db6c93643b1',
    messagingSenderId: '156906942756',
    projectId: 'hardwareos-saas',
    storageBucket: 'hardwareos-saas.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZwl2J6-MQl_ZcRD794yT61FEhp9Sirv4',
    appId: '1:156906942756:web:26c2dab93cf669903643b1',
    messagingSenderId: '156906942756',
    projectId: 'hardwareos-saas',
    authDomain: 'hardwareos-saas.firebaseapp.com',
    storageBucket: 'hardwareos-saas.firebasestorage.app',
    measurementId: 'G-EJGL610LTJ',
  );
}
